server:
  port: 8082

spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  datasource:
    url: jdbc:postgresql://forest_monitoring_postgis_v2:5432/geo_forestry_db
    username: postgres
    password: yB43YS1ee7Iw
    driver-class-name: org.postgresql.Driver
#  datasource:
#    url: jdbc:postgresql://localhost:5433/geo_forestry_db
#    username: postgres
#    password: 123
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    com.yourcompany: DEBUG

websocket:
  endpoint: /ws
  broker:
    destination-prefix: /topic

rest:
  geoforestry:
    base-url: http://localhost:8083